name: NextAgeDdayJS
description: "API 키 없이 로컬 Stash 접속, 다음 나이까지 D-Day를 Custom Field에 저장하는 JS 플러그인"
version: 1.0.0

interface: raw
errLog: info

tasks:
  - name: UpdateNextAgeDday
    displayName: "다음 나이까지 D-Day 업데이트"
    description: "API 키 없이 로컬 Stash 접속하여 배우별 다음 나이까지 D-Day 계산 후 Custom Field에 저장"
    exec:
      - node
      - main.js
