name: NextAgeDdayJS
description: "배우의 다음 나이까지 D-Day를 계산하여 Custom Field에 저장하는 JS 플러그인"
version: 1.0.0

interface: raw
errLog: info

tasks:
  - name: UpdateNextAgeDdayJS
    displayName: "다음 나이까지 D-Day 업데이트 (JS)"
    description: "모든 배우에 대해 다음 나이까지 D-Day를 계산하고 Custom Field에 저장"
    exec:
      - node
      - main.js