name: NextAgeDdayJS
description: "Auto calculate days until next age for performers"
version: 1.0.0

interface: raw
errLog: info

tasks:
  - name: UpdateNextAgeDdayNoKey
    displayName: "Update Next Age D-Day (No API Key)"
    description: "Calculate and save next age D-Day to custom fields"
    exec:
      - node
      - main.js
